version: "3.9" #Version of docker compose syntax.

# Consists of one or more service
services: 
  app: # Name of our service
    build: # Build the docker file inside our current directory
      context: . # use the current directory
      args:
        - DEV=true
    ports:
      - "8000:8000" #Maps our local machine port to port inside the docker container
    volumes:
      - ./app:/app # Mapping our local directory to inside our container directory this
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db # name of the database service
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme4
    depends_on:
      - db


  db:
    image: postgres:13-alpine
    volumes: 
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme4

volumes:
  dev-db-data: #name of the volume
