---
name: Checks #filename

on: [push] #triger - run on push

jobs:
  test-lint: #Job name
    name: Test and Lint
    runs-on: ubuntu-20.04 # the os which github action uses, comes with docker installed
    steps:
      - name: Login to Docker Hub # Action to login to docker
        uses: docker/login-action@v1 #premade action ie setup to login to docker @specifies the version
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Checkout #This action fetch the latest code from the repo and make it available for the subsequent steps
        uses: actions/checkout@v2
      - name: test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db &&  python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"

